Fix Basic Usage example in readme.md
Existing example shows the following:
```app.include_router(CRUDRouter(schema=Potato))```
which cause the following error, because the memory router takes `schema` as a kwarg, not `model`:
```TypeError: __init__() missing 1 required positional argument: 'schema'```